scr_initenemy()
is_controllable = 1
grav = 0.5
hsp = 0
vsp = 0
state = (134 << 0)
stunned = 0
alarm[0] = 150
roaming = 1
collectdrop = 5
flying = 0
straightthrow = 0
cigar = 0
cigarcreate = 0
stomped = 0
shot = 0
reset = 0
hp = 1
hitboxcreate = 0
grounded = 1
flash = 0
slapped = 0
birdcreated = 0
boundbox = 0
important = 0
heavy = 0
depth = 0
paletteselect = 0
spr_palette = palette_forknight
grabbedby = 0
stuntouchbuffer = 0
ragedash = 0
ragecooldown = 0
idlespr = spr_forknight_idle
stunfallspr = spr_forknight_stun
walkspr = spr_forknight_walk
grabbedspr = spr_forknight_grabbed
scaredspr = spr_forknight_scared
spr_dead = spr_forknight_dead
sprite_index = spr_forknight_walk
if ((room == midway_1) || (string_copy(room_get_name(room), 1, 6) == "midway"))
{
    idlespr = spr_forknightBO_walk
    stunfallspr = spr_forknightBO_stun
    walkspr = spr_forknightBO_walk
    grabbedspr = spr_forknightBO_stun
    scaredspr = spr_forknightBO_scared
    spr_dead = spr_forknightBO_dead
    sprite_index = spr_forknightBO_walk
}
