var lay_id = layer_get_id("Backgrounds_1")
var back_id = layer_background_get_id(lay_id)
var lay_id2 = layer_get_id("Backgrounds_2")
var back_id2 = layer_background_get_id(lay_id2)
var lay_id3 = layer_get_id("Backgrounds_3")
var back_id3 = layer_background_get_id(lay_id3)
if ((global.panic == true) && (layer_background_get_sprite(back_id) == 1766))
    layer_background_sprite(back_id, spr_kingghost_anchor)
if ((global.panic == true) && (layer_background_get_sprite(back_id) == 1763))
    layer_background_sprite(back_id, spr_spinningquestionmark)
if ((global.panic == true) && (layer_background_get_sprite(back_id3) == 1770))
    layer_background_sprite(back_id3, tile_bigrocks)
if ((global.panic == true) && (layer_background_get_sprite(back_id) == 1715))
    layer_background_sprite(back_id, spr_indiancheese_turn)
if ((global.panic == true) && (layer_background_get_sprite(back_id) == 1719))
    layer_background_sprite(back_id, spr_mortdead)
if ((global.panic == true) && (layer_background_get_sprite(back_id2) == 1723))
    layer_background_sprite(back_id2, spr_timedgate)
if ((global.panic == true) && (layer_background_get_sprite(back_id) == 1824))
    layer_background_sprite(back_id, spr_parryhitbox)
if ((global.panic == true) && (layer_background_get_sprite(back_id2) == 1822))
    layer_background_sprite(back_id2, bg_mansionplain)
if ((global.panic == true) && (layer_background_get_sprite(back_id3) == 1818))
    layer_background_sprite(back_id3, spr_plains1)
