image_speed = 0.1
chose = 0
message = ""
showtext = 0
tvprompts_list = ds_list_create()
state = (0 << 0)
promptxstart = 641
promptx = promptxstart
prompt = ""
promptspd = 1
prompt_buffer = 0
prompt_max = 150
promptsurface = surface_create(290, 102)
tvbg_surface = surface_create(278, 268)
surface_set_target(tvbg_surface)
draw_clear_alpha(c_black, 0)
surface_reset_target()
goo_index = 0
goo_surface = surface_create(100, 180)
surface_set_target(goo_surface)
draw_clear_alpha(c_black, 0)
surface_reset_target()
targetgolf = -4
special_prompts = -4
hud_posx = 0
hud_posY = 0
if ((obj_player1.state != "PZ"))
    combo_state = 0
else
    combo_state = 112
combo_posX = 0
combo_vsp = 0
combo_posY = 0
combofill_x = 0
combofill_y = 0
combofill_index = 0
noisemax = 16
noisebuffer = noisemax
expressionsprite = -4
expressionbuffer = 0
golfsurf = -4
if ((obj_player1.character != "PZ"))
    tvsprite = spr_tv_idle
else
    tvsprite = spr_tvoffSP
sprite_index = spr_tv_off
bubbleindex = 0
bubblespr = -4
idleanim = 180
noisesprite = spr_noiseHUD_idle
xi = 500
yi = 600
imageindexstore = 0
once = 0
global.hurtcounter = 0
global.hurtmilestone = 3
alpha = 1
shownranka = 0
shownrankb = 0
shownrankc = 0
collect_shake = 0
global.srank = 0
global.arank = 0
global.brank = 0
global.crank = 0
character = "PEPPINO"
display_set_gui_size(960, 540)
chunkmax = 0
timer_xstart = 327
timer_ystart = 464
timer_x = timer_xstart
timer_y = (timer_ystart + 212)
pizzaface_sprite = spr_timer_pizzaface1
pizzaface_index = 0
johnface_sprite = spr_timer_johnface
johnface_index = 0
hand_sprite = spr_timer_hand1
hand_index = 0
bar_surface = -4
barfill_x = 0
showtime_buffer = 0
tv_trans = 0
roll_index = 0
roll_sprite = spr_bartimer_roll
bartimer_x = 0
coneball_index = 0
coneball_sprite = spr_bartimer_normalBack
timer_out = 180
timer_in = 180
timer_ySP = 100
target_fill = 0
propindex = 0
static_index = 0
statictimer = 0
staticdraw = 0
draw_static = 0
DrawX = 0
OldDrawY = 0
DrawY = 0
bobbing = 0
tvspr = spr_pizzelletv_new
hand_y = 0
hand_x = 0
combo_x = 0
combo_y = 0
combo_vsp = 0
ComboShake = 0
draw_combo = 0
frameref = 0
checkpointspr = spr_checkpointflag_unvisit
checkpointalpha = 0
checkpointindex = 0
