if ((global.timeattack == 1))
    instance_destroy()
if ((ds_list_find_index(global.saveroom, id) != -1))
    instance_destroy()
if ((content == 566) && global.shroomfollow)
    instance_destroy()
if ((content == 567) && global.cheesefollow)
    instance_destroy()
if ((content == 568) && global.tomatofollow)
    instance_destroy()
if ((content == 570) && global.sausagefollow)
    instance_destroy()
if ((content == 571) && global.pineapplefollow)
    instance_destroy()
if ((global.snickchallenge == 1))
    instance_destroy()
