if (!global.panic)
{
    lay_id = layer_get_id("Backgrounds_2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3402))
        layer_background_sprite(back_id, bg_waferback2)
    lay_id = layer_get_id("Backgrounds_2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3448))
        layer_background_sprite(back_id, bg_entryway2_buildings)
    lay_id = layer_get_id("Backgrounds_1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3403))
        layer_background_sprite(back_id, bg_waferback1)
    lay_id = layer_get_id("Backgrounds_1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3437))
        layer_background_sprite(back_id, bg_entryway2_buildings2)
    lay_id = layer_get_id("Backgrounds_stillscroll")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3445))
        layer_background_sprite(back_id, bg_entryway2_clouds)
    lay_id = layer_get_id("Backgrounds_scroll")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3405))
        layer_background_sprite(back_id, bg_waferclouds)
    lay_id = layer_get_id("Backgrounds_still2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3406))
        layer_background_sprite(back_id, bg_wafersun)
    lay_id = layer_get_id("Backgrounds_still2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3446))
        layer_background_sprite(back_id, bg_entryway2_sun)
    lay_id = layer_get_id("Backgrounds_still1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3409))
        layer_background_sprite(back_id, bg_wafersky)
    lay_id = layer_get_id("Backgrounds_still1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3447))
        layer_background_sprite(back_id, bg_entryway2_sky)
}
if global.panic
{
    lay_id = layer_get_id("Backgrounds_2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3383))
        layer_background_sprite(back_id, bgwafer_escape1)
    lay_id = layer_get_id("Backgrounds_2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3432))
        layer_background_sprite(back_id, bg_escapebuildingsentryway)
    lay_id = layer_get_id("Backgrounds_1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3382))
        layer_background_sprite(back_id, bgwafer_escape2)
    lay_id = layer_get_id("Backgrounds_1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3433))
        layer_background_sprite(back_id, bg_escapebuildingsentryway2)
    lay_id = layer_get_id("Backgrounds_stillscroll")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3434))
        layer_background_sprite(back_id, bg_entrywayescapeclouds)
    lay_id = layer_get_id("Backgrounds_scroll")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3384))
        layer_background_sprite(back_id, bgwafer_escape3)
    lay_id = layer_get_id("Backgrounds_still2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3386))
        layer_background_sprite(back_id, bgwafer_escape4)
    lay_id = layer_get_id("Backgrounds_still2")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3436))
        layer_background_sprite(back_id, bg_entrywayescapemoon)
    lay_id = layer_get_id("Backgrounds_still1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3385))
        layer_background_sprite(back_id, bgwafer_escape5)
    lay_id = layer_get_id("Backgrounds_still1")
    back_id = layer_background_get_id(lay_id)
    if ((layer_background_get_sprite(back_id) == 3435))
        layer_background_sprite(back_id, bg_entrywaynightsky)
    alarm[1] = 1
}
alarm[1] = 1
